CREATE TABLE readings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id   VARCHAR(255),
    location    VARCHAR(255),
    temperature DOUBLE PRECISION,
    humidity    INTEGER,
    heat_index  DOUBLE PRECISION,
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    message     VARCHAR(255),
    CONSTRAINT pk_readings PRIMARY KEY (id)
);